name: v_player
description: "A beautiful music player app."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.43
  just_audio_background: any
  audio_session: ^0.1.21
  permission_handler: ^11.3.1
  palette_generator: ^0.3.3+3
  google_fonts: ^6.2.1
  provider: ^6.1.2
  wave_blob: ^1.0.5
  shared_preferences: ^2.2.3
  miniplayer: any
  audio_waveforms: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
